In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
import sys

In [7]:
# importing datasets
GCIAI = pd.read_excel("AI_GCI.xlsx")
Shares = pd.read_excel("Shares.xlsx")
PCShip = pd.read_excel("PCShipment.xlsx")

   Year  Shipments (Millions)
0  2019               267.667
1  2020               302.605
2  2021               339.769
3  2022               286.197
4  2023               241.900

In [12]:
merged = pd.merge(GCIAI,Shares, on="Year")

In [13]:
merged2 = pd.merge(merged, PCShip, on="Year")

In [14]:
merged2.head()

,Year,GCI in AI (billions),HBM_Share,DRAM_PerPC,DRAMPrice,Shipments (Millions)
0,2019,103.27,0.0,9.2,4.3,267.667
1,2020,221.87,0.0,10.5,2.9,302.605
2,2021,360.73,0.3,11.8,3.4,339.769
3,2022,253.25,0.8,12.4,2.8,286.197
4,2023,201.00,2.0,13.1,2.0,241.900

In [16]:
merged2 = merged2.rename(columns={"GCI in AI (billions)": "GCI_AI", "Shipments (Millions)": "Shipments"})
merged2.head()

   Year  GCI_AI  HBM_Share  DRAM_PerPC  DRAMPrice  Shipments
0  2019  103.27        0.0         9.2        4.3    267.667
1  2020  221.87        0.0        10.5        2.9    302.605
2  2021  360.73        0.3        11.8        3.4    339.769
3  2022  253.25        0.8        12.4        2.8    286.197
4  2023  201.00        2.0        13.1        2.0    241.900

In [17]:
reg1 = smf.ols("DRAMPrice ~ Shipments + GCI_AI", data=merged2).fit()
reg2 = smf.ols("DRAMPrice ~ HBM_Share + DRAM_PerPC + Shipments", data=merged2).fit()

In [18]:
print(reg1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              DRAMPrice   R-squared:                       0.593
Model:                            OLS   Adj. R-squared:                  0.389
Method:                 Least Squares   F-statistic:                     2.911
Date:                Tue, 30 Jun 2026   Prob (F-statistic):              0.166
Time:                        08:41:22   Log-Likelihood:                -5.9630
No. Observations:                   7   AIC:                             17.93
Df Residuals:                       4   BIC:                             17.76
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -1.2454      2.517     -0.495      0.647      -8.233       5.742
Shipments      0.0178      0.009      1.948      0.123      -0.008       0.043
GCI_AI        -0.0037      0.002     -1.800      0.146      -0.009       0.002
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.756
Prob(Omnibus):                    nan   Jarque-Bera (JB):                1.125
Skew:                           0.975   Prob(JB):                        0.570
Kurtosis:                       2.762   Cond. No.                     3.65e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.65e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\Ben\anaconda3\Lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 7 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "

In [19]:
print(reg2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              DRAMPrice   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.770
Method:                 Least Squares   F-statistic:                     7.712
Date:                Tue, 30 Jun 2026   Prob (F-statistic):             0.0637
Time:                        08:41:50   Log-Likelihood:                -1.5305
No. Observations:                   7   AIC:                             11.06
Df Residuals:                       3   BIC:                             10.84
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      7.1112      2.714      2.620      0.079      -1.527      15.749
HBM_Share      0.6555      0.274      2.389      0.097      -0.218       1.529
DRAM_PerPC    -0.7125      0.238     -2.994      0.058      -1.470       0.045
Shipments      0.0128      0.006      2.058      0.132      -0.007       0.033
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   2.773
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.859
Skew:                          -0.852   Prob(JB):                        0.651
Kurtosis:                       2.793   Cond. No.                     4.41e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.41e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\Ben\anaconda3\Lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 7 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "